INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Crear Sprint Backlog');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Asignar Tareas');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Realizar Pruebas de Integración');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Escribir Documentación');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Realizar Pruebas de Aceptación');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Realizar Revisión de Código');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Estimar Tareas');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Planificar Iteraciones');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Definir Historias de Usuario');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Desplegar Aplicación');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Realizar Pruebas Unitarias');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Realizar Pruebas de Regresión');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Gestionar Requerimientos');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Realizar Reuniones de Equipo');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Gestionar Incidencias');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Configurar Ambiente de Desarrollo');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Realizar Capacitación del Equipo');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Realizar Estudios de Factibilidad');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Gestionar Cambios de Requerimientos');
INSERT INTO funcion (id_funcion, nombre_funcion) VALUES (NULL, 'Realizar Pruebas de Usabilidad');