INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '0', 'Me sentí muy satisfecho con el trabajo realizado durante este sprint.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '1', 'Me siento cansado después de este sprint, pero orgulloso de lo que hemos logrado.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '0', 'Estoy contento con los resultados de este sprint y me siento motivado para seguir trabajando.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '1', 'Realmente no me gusta trabajar en sprints tan cortos, me siento presionado y estresado.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '0', 'Me sentí un poco abrumado al principio, pero al final del sprint, me sentí satisfecho con lo que logramos.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '1', 'Siento que este sprint fue muy difícil y no estoy seguro de si pudimos cumplir con todas las tareas.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '0', 'Me siento feliz y emocionado por todo lo que hemos logrado durante este sprint.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '1', 'Estoy un poco decepcionado con los resultados de este sprint y siento que podríamos haber hecho más.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '0', 'Me sentí un poco agobiado durante este sprint, pero estoy contento con los resultados finales.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '1', 'Siento que este sprint fue demasiado fácil y me gustaría tener más desafíos en el futuro.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '0', 'Me siento muy motivado y entusiasmado después de este sprint.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '1', 'Realmente no me gusta trabajar en equipo durante los sprints y prefiero trabajar solo.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '0', 'Me siento muy orgulloso de mi equipo y de lo que hemos logrado durante este sprint.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '1', 'Siento que el sprint fue demasiado corto y no tuvimos suficiente tiempo para completar todas las tareas.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '0', 'Me sentí un poco abrumado al principio, pero al final del sprint, me sentí satisfecho con lo que logramos.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '1', 'Siento que hubo muchos obstáculos durante este sprint que nos impidieron lograr nuestras metas.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '0', 'Estoy contento con mi desempeño durante este sprint y siento que he aprendido mucho.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '1', 'Me siento frustrado porque no pudimos completar todas las tareas que nos propusimos para este sprint.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '0', 'Me siento muy motivado para mejorar en las áreas en las que no me fue tan bien durante este sprint.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '1', 'Siento que la comunicación en el equipo no fue buena durante este sprint y eso nos afectó negativamente.');
INSERT INTO respuesta (id_respuesta, anonimo, respuesta) VALUES (NULL, '0', 'Me sentí muy cómodo trabajando con mi equipo durante este sprint y creo que hicimos un buen trabajo juntos.');