INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'puede ser');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'no');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'feliz');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'mas tiempo');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'si');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'mejor');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'mas esfuerzo');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'puede ser');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'feliz');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'no');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'si');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'mejor');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'mas tiempo');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'mas esfuerzo');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'puede ser');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'feliz');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'no');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'mejor');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'mas tiempo');
INSERT INTO opcion_respuesta (id_opcion_respuesta, opcion_respuesta) VALUES (NULL, 'mas esfuerzo');