INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (1, 'Como te sentiste en este sprint?', 1, 14),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (2, 'Te gustó este sprint?', 1, 15),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (3, 'Dime tu opinión del sprint', 1, 11),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (4, 'Crees que hubo mejora a comparacion con el pasado?', 1, 11),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (5, 'Selecciona lo que aplique:', 0, 14),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (6, 'Del 1 al 5, que tanto has disfrutado este epic', 1, 14),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (7, 'Como te sentiste en este epic?', 1, 14),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (8, 'Te gustó este epic?', 1, 15),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (9, 'Crees que hubo mejora a comparacion con el pasado?', 1, 11),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (10, 'Tienes buenos amigos en la empresa?', 0, 15),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (11, 'Consideras el epic adecuado?', 0, 11),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (12, 'Consideras alguna mejora en el avance?', 0, 11),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (13, 'Como sentiste el trabajo colaborativo?', 1, 14),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (14, 'Como sentiste la carga de trabajo?', 1, 14),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (15, 'Te sientes comodo en tu equipo?', 1, 14),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (16, 'Te sentiste enojado?', 0, 15),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (17, 'Te sentiste ansioso?', 0, 15),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (18, 'Te sentiste triste?', 0, 15),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (19, 'Te sentiste feliz?', 0, 15),
INSERT INTO pregunta (id_pregunta, pregunta, predeterminada, id_tipo_pregunta) VALUES (20, 'Alguna cosa que quieras implementar?', 1, 11);
